---
title: "Covid-19 Policy Helper"
date: Aug 2020
author: "Xinyi Lai, Yulin Li"
output: 
  html_document: 
    theme: readable
    toc: yes
    toc_depth: 3
    number_sections: no
urlcolor: cyan
editor_options: 
  chunk_output_type: inline
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
options(scipen = 1, digits = 4, width = 80)
library(knitr)
opts_chunk$set(cache = TRUE, autodep = TRUE)
```


## Data Preprocessing

```{r}
library(readr)
county_data_abridged = read_csv("county_data_abridged.csv")
```

### County-Level Demographic Data

```{r eval=FALSE, include=FALSE}
View(county_data_abridged)
```

```{r}
dim(county_data_abridged)
names(county_data_abridged)

# county_data_abridged$
```


```{r}
# data = subset(county_data_abridged, 
#               select = c(CountyName, StateName, POP_LATITUDE, POP_LONGITUDE, HPSAPercentPoverty， 
#                          PopulationEstimate2018， PopulationEstimate65+2017， PopTotalMale2017， PopTotalFemale2017， PopulationDensityperSqMile2010，"#EligibleforMedicare2018"，))
```


```{r}
# county_data_abridged[1, 22] = "EligibleforMedicare2018"
str(county_data_abridged)
```


```{r, warning=FALSE}




# # remove missing data, which is stored as "NA"
# data = na.omit(data)
# 
# 
# 
# # get rid of the messy codes in the floor variable and coerce the results to numeric values
# dat$floor = as.numeric(matrix(unlist(strsplit(dat$floor, " ")), ncol = 2, byrow = TRUE)[ , 2])
# # remove the variables we are not interested in such as url and transaction id
# dat = subset(dat, select = c(price, square, livingRoom, drawingRoom, kitchen, bathRoom, floor, buildingType, constructionTime, renovationCondition, buildingStructure, ladderRatio, elevator, subway, district))
# # coerce the categorical predictors to factor variables
# dat$buildingType = as.factor(dat$buildingType)
# dat$renovationCondition = as.factor(dat$renovationCondition)
# dat$buildingStructure = as.factor(dat$buildingStructure)
# dat$elevator = as.factor(dat$elevator)
# dat$subway = as.factor(dat$subway)
# dat$district = as.factor(dat$district)
# # coerce constructionTime to numeric variable (originally character type)
# dat$constructionTime = as.numeric(dat$constructionTime)
# # remove missing values again since some of the preceding steps resulting in new NA values
# dat = na.omit(dat)
# # extract data of houses built after 2010 and drop all redundant levels in the categorical predictors
# dat = subset(dat, constructionTime > 2010)
# dat = droplevels(dat)
```



### County-Level Policy Data

```{r}
timeseries = read_csv("timeseries.csv")
```

```{r}
str(timeseries)
```


### County-Level Infection Data 

#### Cases Data
```{r}

```

#### SEIR Model Parameters
```{r}

```



